#!/usr/bin/bash

declare -A app_menu

# associative array : [pangu markup of program]=program path name
app_menu=(
    ["AdventureQuest <small><i>(aq)</i></small>"]="aqclassic_launcher-linux-x64/aqclassic_launcher"
    ["Firefox"]="firefox"
    ["Calibre <small><i>(epub book viewer)</i></small>"]="calibre"
    ["Conky"]="conky"
    ["Discord"]="discord"
    ["KeePassXC <small><i>(password manager)</i></small>"]="keepassxc"
    ["Rxvt <small><i>(urxvt terminal emulator)</i></small>"]="urxvt"
    ["Lxappearance <small><i>(theme switcher)</i></small>"]="lxappearance"
    ["PCManFM <small><i>(file manager)</i></small>"]="pcmanfm"
    ["Google Chrome"]="google-chrome-stable"
    ["Font Manager"]="font-manager"
    ["VSCode"]="code"
    ["anki"]="anki"
    ["feh <small><i>(image viewer)</i></small>"]="feh"
)

if [ $# -eq 0 ]; then
    # set prompt
    echo -en "\0prompt\x1fsearch app:\n"

    # add markup prefix
    for i in "${!app_menu[@]}"
    do
        echo -en "\x00markup-rows\x1ftrue\n$i"
    done
else
    # launch program as coproc
    coproc (${app_menu[$1]} > /dev/null 2>&1 )
    exit 0
fi
