#!/usr/bin/bash

declare -A app_menu

# associative array : [pangu markup of program]=program path name
app_menu=(
    ["Firefox"]="firefox" 
    ["Conky"]="conky" 
    ["Discord"]="discord"
    ["KeePassXC <small><i>(password manager)</i></small>"]="keepassxc"
    ["Rxvt <small><i>(urxvt terminal emulator)</i></small>"]="urxvt"
    ["Lxappearance <small><i>(theme switcher)</i></small>"]="lxappearance"
    ["Nautilus <small><i>(file manager)</i></small>"]="nautilus"
    ["Sublime Text <small><i>(code/text editor)</i></small>"]="subl"
    ["Google Chrome"]="google-chrome-stable"
    ["Adventure Quest"]="adventure-quest"
)

if [ $# -eq 0 ]; then
    # set prompt
    echo -en "\0prompt\x1fsearch app:\n"

    # add markup prefix
    for i in "${!app_menu[@]}"
    do
        echo -en "\x00markup-rows\x1ftrue\n$i"
    done
else
    # launch program as coproc
    coproc (${app_menu[$1]} > /dev/null 2>&1 )
    exit 0
fi

