#!/usr/bin/bash
# https://github.com/davatorium/rofi-scripts/blob/master/mode-scripts/rofi-file-browser.sh

echo -en "\0prompt\x1fsearch files:\n"

EDITOR=code

CUR_DIR=~/
PREV_LOC_FILE=~/.config/rofi/rofi_prev_loc

if [ $# -eq 0 ] # launching confing menu for the first time with no args
then
    echo "$CUR_DIR" > "$PREV_LOC_FILE" # init "$PREV_LOC_FILE" to ~/
else
    CUR_DIR=$(cat "$PREV_LOC_FILE")

    if [ "$1" = "." ] # open editor in current directory
    then
        coproc ("$EDITOR" "$CUR_DIR" > /dev/null 2>&1)
        exit 0
    elif [ "$1" = ".." ] # go back
    then
        CUR_DIR="$(dirname "$CUR_DIR")/"
        echo "$CUR_DIR" > "$PREV_LOC_FILE"
    else
        CUR_DIR+="$@"

        if [ -d "$CUR_DIR" ] # selected directory
        then 
            echo "$CUR_DIR" > "$PREV_LOC_FILE"
        else
            coproc ("$EDITOR" "$CUR_DIR" > /dev/null 2>&1)
            exit 0;
        fi
    fi

    if [ "$CUR_DIR" != ~/ ]
    then
        echo "."
        echo ".."
    fi
fi

ls "$CUR_DIR" --almost-all  --group-directories-first --color=never --indicator-style=slash