#!/usr/bin/env bash

## Author  : Aditya Shakya
## Github  : @adi1090x

theme="card_circle"
dir="$HOME/.config/rofi/powermenu"

rofi_command="rofi -theme $dir/$theme"

# Options

lock=""
suspend=""
logout=""
reboot=""
shutdown=""

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command  -dmenu -selected-row 1)"

case $chosen in
    $shutdown)
		systemctl poweroff
        ;;
    $reboot)
		systemctl reboot
        ;;
    $lock)
		lock-screen
        ;;
    $suspend)
		systemctl suspend
        ;;
    $logout)
		i3-msg exit
        ;;
esac